services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: postgres:14.12
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
    
volumes:
  db:
